name: Blob storage website CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
    - name: Azure CLI script
      uses: actions/checkout@v2
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and npm run build
      run: |
          npm ci
          npm run build
