name: Blob storage website CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
    - name: Azure CLI script
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and npm run build
      run: |
          npm ci
          npm run build

     
    - name: Run Az CLI script  
      run: |
        az storage blob upload-batch --account-name 'azureapimanagementplanb' -s ./build -d '$web'
        # Azure logout 
    - name: logout
      run: |
            az logout
